### ISSUE TITLE
Crear Archivo HTML del dashboard

### ISSUE THREAD

**Issue by themarshial** [themarshial/proyecto-3#1]
one person

**Comment by themarshial** [comment]
Hola Gus , tienes trabajo xd, es crear el archivo html ,esquematizado creo que asi se dice , es decir con las etiquetas y asi como el diseño de Yasser, cualquier duda al grupo lo dices. Manos a la obra! :)

**Comment by Gustav0218** [comment]
Hola! 
Sigo tenineod problemas para abrir el issue.  El "Open" me lo marca en rojo. 
Seguire haciendo el HTML. 
Pero quen podemos hacer con eso ?
